export enum CommandType {
  COMMAND_START = 'e-start',
  COMMAND_INIT = 'e-init',
  COMMAND_ALL_PART = 'e-part',
  COMMAND_ALL_TEST = 'e-test',
  COMMAND_ALL_TOPIC = 'e-topic',
  COMMAND_HELP = 'e-help',
  COMMAND_PROFILE = 'e-profile',
  COMMAND_ALL_VOCABULARY_OF_USER = 'e-my-vocab',
  COMMAND_MY_PROGRESS = 'e-my-progress',
  COMMAND_GENERATE_TEXT = 'gen-text',
  COMMAND_ELAKOTHE = 'e-lakhongthe',

  SELECT_PART = 'toeic-part',
  SELECT_TEST = 'toeic-test',

  BUTTON_CONFIRM_START_TEST = 'start-test',
  BUTTON_NEXT_QUESTION = 'next-question',
  BUTTON_CANCEL_TEST = 'cancel-test',
  BUTTON_USER_ANSWER = 'user-answer',
  BUTTON_SHOW_VOCABULARY = 'show-vocabulary',
  BUTTON_CONTINUE_TEST = 'continue-test',
  BUTTON_RESTART_TEST = 'restart-test',
  BUTTON_SAVE_VOCABULARY = "save-vocabulary",
  BUTTON_NEXT_PART = 'next-part',
  BUTTON_REVIEW_TEST = 'review-test',
  BUTTON_SHOW_VOCABULARY_PREV = 'show-vocabulary-prev',
  BUTTON_SHOW_VOCABULARY_NEXT = 'show-vocabulary-next',
  BUTTON_DELETE_MY_VOCABULARY = 'delete-my-vocabulary',
  BUTTON_GUESS_WORD_ANSWER = 'word-answer'
}