export enum BadgeEnum {
  MASTER_OF_10 = "🎯 Master of 10",
  ACCURACY_PRO = "🔥 Accuracy Pro",
  STREAK_7 = "🏆 7-day Streak",
  CENTURY_PLAYER = "💎 Century Player",
  STREAK_30 = "🌟 30-day Streak",
  POINTS_500 = "💥 500 Points Hero",
  POINTS_1000 = "👑 Ultimate Player",
  CORRECT_100 = "🧠 Quiz Expert",
  CORRECT_500 = "🚀 Quiz Legend",
  PART_FINISHER = "🧩 Part Finisher",
  PERFECT_PART = "🌈 Perfect Part",
  TEST_FINISHER = "📘 Test Finisher",
  PERFECT_TEST = "🏅 TOEIC Master",
}
